### ISSUE TITLE
missing repos

### ISSUE THREAD

**Issue by ghost** [rep/dionaea#12]
git clone git://git.carnivore.it/liblcfg.git liblcfg
git clone git://git.carnivore.it/libemu.git libemu
git clone git://git.infradead.org/users/tgr/libnl.git

how do i proceed?

**Comment by mshirley** [comment]
If you're going to rely on this software you should create your own git forks so you'll always have a working copy.

git clone https://github.com/gento/liblcfg
git clone https://github.com/buffer/libemu
git clone https://github.com/thom311/libnl

**Comment by ghost** [comment]
thank you
