### ISSUE TITLE
Logging to XMPP (Prosody) Backend

### ISSUE THREAD

**Issue by Theory5** [rep/dionaea#6]
Hello!

I have enjoyed using Dionaea. I am attempting to build a network of systems that feed into a SIEM (among other things) and I require Dionaea XMPP logging. I setup prosody, and I can connect to it via my pidgin client on my desktop, but I cannot get my EC2 instance Dionaea program to connect to it! It opens a connection, then prosody closes it with this error:

Sep 22 14:52:21 socket  debug   server.lua: accepted new client connection from <instance IP and random port> to 5222
Sep 22 14:52:21 c2s1d928e0      info    Client connected
Sep 22 14:52:21 mod_c2s debug   Received invalid XML (not well-formed (invalid token)) 214 bytes: ____�___�__T o�;_Y�B�_3�d�z_�_(�!�_____�� W__Z�_� _9_8_�_��_�**5_��_�**$
Sep 22 14:52:21 c2s1d928e0      debug   Disconnecting client, stream:error is: stream:error<not-well-formed xmlns='urn:ietf:params:xml:ns:xmpp-streams'/></stream:err$
Sep 22 14:52:21 c2s1d928e0      info    c2s stream for <Instance IP> closed: not-well-formed
Sep 22 14:52:21 c2s1d928e0      debug   Destroying session for (unknown) ((unknown)@(unknown)): not-well-formed
Sep 22 14:52:21 c2s1d928e0      info    Client disconnected: connection closed
Sep 22 14:52:21 c2s1d928e0      debug   Destroying session for (unknown) ((unknown)@(unknown))
Sep 22 14:52:21 socket  debug   server.lua: closed client handler and removed socket from list

I thought I've tried everything, every which way but it doesn't work no matter what I try. I am stuck. Any assistance would be awesome. I'm using the latest version of prosody.

**Comment by Zash** [comment]
Is it trying to do TLS without negotiation, aka Legacy SSL"? That would be my first guess.

**Comment by Theory5** [comment]
Yes. I thought that's what the documentation said to do, something about dionaea not being able to negotiate TLS. 

So I just have to set it up with TLS?

**Comment by Zash** [comment]
I'm guessing you'll need to enable legacy ssl, `legacy_ssl_ports = { 5223 }` in your prosody config.

**Comment by Theory5** [comment]
It's enabled. I'll post my config files when I am home.

**Comment by Zash** [comment]
And then point Dionaea to port 5223 instead of 5222.

Btw, [this comment](https://github.com/rep/dionaea/blob/6756787f94c4f1ac53d1e5545d052774a0446c04/conf/dionaea.conf.dist#L377-L381) seems to have the ports backwards, it's usually starttls on 5222 and legacy ssl on 5223.

**Comment by Theory5** [comment]
This is the prosody log after I did that:
http://pastebin.com/ExtwSbCr

Prosody config:
http://pastebin.com/pg5fuiY8

My dionaea:

http://pastebin.com/XxPmyEkV

I am unsure how to proceed troubleshooting

**Comment by Zash** [comment]
`legacy_ssl_ports` needs to be in the global section (i.e. above all `VirtualHost` lines).

**Comment by Theory5** [comment]
Finally! Thanks for the help!

**Comment by Infywebrtcdev1** [comment]
s

**Comment by Infywebrtcdev1** [comment]
hi zash

Prosody and nginx is running 

and when i hit this url on browser 
 http://192.168.1.4:5280/xmpp-websocket

i m getting this. 
It works! Now point your WebSocket client to this URL to connect to Prosody.

this is working fine 

but when i m trying to establish the connection using android code using smack-3.1.0.jar
with following configuration.

final ConnectionConfiguration   config = new ConnectionConfiguration("192.168.1.4", 5280,"192.168.1.4");
        //config.setSecurityMode(SecurityMode.enabled);
        config.setReconnectionAllowed(true);
        config.setRosterLoadedAtLogin(true);
        config.setSendPresence(false);
        config.setSocketFactory(SSLSocketFactory.getDefault());

```
    // NOTE: Set to true to launch a window with information about packets
    // sent and received
    //config.setDebuggerEnabled(true);

    // -Dsmack.debugEnabled=true
    XMPPConnection.DEBUG_ENABLED = true;
    final XMPPConnection connection= new XMPPConnection(config);;
    SASLAuthentication.supportSASLMechanism("PLAIN",0);
    config.setSASLAuthenticationEnabled(true);


           connection.connect();

          connection.login(username, password);
```

then i m getting on prosody side 

Apr 28 12:26:26 socket  debug   server.lua: accepted new client connection from 192.168.1.4:39666 to 5280

only this log is coming.

so please can u help me to establish a successful connection.so i can able to send msgs .
Any help is appreciated.
Thanks in advance.
